server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?user=postgres.hqkliimgwllzcbdsqhcq&password=YHNQNqkjaaDmuhT8
    username: postgres
    password: YHNQNqkjaaDmuhT8
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        boot:
          allow_jdbc_metadata_acess: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://hqkliimgwllzcbdsqhcq.supabase.co/auth/v1